name: Seasoning Converter CICD

on: 
  push:
    branches:
      - main
    paths:
      - src/**
  workflow_dispatch:

env:
  AWS_REGION : "ap-northeast-1"

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  
jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone the repository
      uses: actions/checkout@v4
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}
    - name: AWS access test
      run: |
        aws ec2 describe-vpcs
        
        
      
        
          
